"""Render the Helm chart with `helm template` and assert it is hardened (PROJECT.md §13.5, §13.2).

These tests shell out to the `helm` binary and are skipped when it is absent (e.g. minimal CI
images). `helm template` is slower than the global fail-slow budget, so each test raises its own.
"""

from __future__ import annotations

import base64
import json
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

pytestmark = pytest.mark.integration

CHART_DIR = Path(__file__).resolve().parents[2] / "deployment" / "helm" / "chart"

_OTLP_ENDPOINT = "config.telemetry.otlpEndpoint=10.1.2.3:4317"
_BASIC_AUTH_SECRET = "basicAuth.secretName=relay-basic-auth"


def _helm_available() -> bool:
    return shutil.which("helm") is not None


requires_helm = pytest.mark.skipif(not _helm_available(), reason="helm binary not installed")


def _render(*set_values: str) -> list[dict]:
    args = ["helm", "template", "rel", str(CHART_DIR)]
    for value in (_OTLP_ENDPOINT, _BASIC_AUTH_SECRET, *set_values):
        args += ["--set", value]
    out = subprocess.run(args, capture_output=True, text=True, check=True, timeout=30)
    return [doc for doc in yaml.safe_load_all(out.stdout) if doc]


def _by_kind(docs: list[dict], kind: str) -> list[dict]:
    return [d for d in docs if d.get("kind") == kind]


@requires_helm
@pytest.mark.fail_slow("30s")
def test_chart_lints_clean() -> None:
    result = subprocess.run(
        ["helm", "lint", str(CHART_DIR), "--set", _BASIC_AUTH_SECRET],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, result.stdout + result.stderr


@requires_helm
@pytest.mark.fail_slow("30s")
def test_deployment_is_hardened() -> None:
    deploy = _by_kind(_render(), "Deployment")[0]
    spec = deploy["spec"]["template"]["spec"]
    pod_sc = spec["securityContext"]
    assert pod_sc["runAsNonRoot"] is True
    assert pod_sc["seccompProfile"]["type"] == "RuntimeDefault"

    container = spec["containers"][0]
    csc = container["securityContext"]
    assert csc["runAsNonRoot"] is True
    assert csc["readOnlyRootFilesystem"] is True
    assert csc["allowPrivilegeEscalation"] is False
    assert csc["capabilities"]["drop"] == ["ALL"]

    assert container["livenessProbe"]["httpGet"]["path"] == "/liveness"
    assert container["readinessProbe"]["httpGet"]["path"] == "/readiness"
    # Read-only root filesystem requires a writable /tmp emptyDir.
    assert any(v.get("emptyDir") is not None and v["name"] == "tmp" for v in spec["volumes"])


@requires_helm
@pytest.mark.fail_slow("30s")
def test_configmap_has_no_secrets() -> None:
    cm = _by_kind(_render(), "ConfigMap")[0]
    relay = json.loads(cm["data"]["relay.json"])
    assert "channels" in relay
    blob = json.dumps(cm["data"]).lower()
    for forbidden in ("keyring", "password", "client-key", "subscription_key", "soap_security"):
        assert forbidden not in blob


@requires_helm
@pytest.mark.fail_slow("30s")
def test_no_networkpolicy_rendered() -> None:
    # NetworkPolicy was removed from the chart (its default ingress rule was allow-all — an empty
    # `from:` matches all sources). Network segmentation is delegated to cluster/cloud controls.
    out = subprocess.run(
        ["helm", "template", "rel", str(CHART_DIR), "--set", _OTLP_ENDPOINT, "--set", _BASIC_AUTH_SECRET],
        capture_output=True,
        text=True,
        check=True,
        timeout=30,
    )
    assert "kind: NetworkPolicy" not in out.stdout


@requires_helm
@pytest.mark.fail_slow("30s")
def test_basic_auth_enabled_without_secret_fails_render() -> None:
    result = subprocess.run(
        ["helm", "template", "rel", str(CHART_DIR), "--set", _OTLP_ENDPOINT],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode != 0
    assert "basicAuth.secretName is required" in (result.stdout + result.stderr)


@requires_helm
@pytest.mark.fail_slow("30s")
def test_basic_auth_disabled_renders() -> None:
    docs = _render("basicAuth.enabled=false", "config.env.RELAY_BASIC_AUTH_ENABLED=false")
    deploy = _by_kind(docs, "Deployment")[0]
    container = deploy["spec"]["template"]["spec"]["containers"][0]
    env_names = {e["name"] for e in container["env"]}
    assert "RELAY_BASIC_AUTH_USER" not in env_names
    assert "RELAY_BASIC_AUTH_PASS" not in env_names


@requires_helm
@pytest.mark.fail_slow("30s")
def test_pii_keyring_secret_is_create_if_absent() -> None:
    secret = _by_kind(_render(), "Secret")[0]
    # Never deleted/regenerated by helm lifecycle.
    assert secret["metadata"]["annotations"]["helm.sh/resource-policy"] == "keep"
    keyring = json.loads(base64.b64decode(secret["data"]["keyring.json"]))
    epoch, key_b64 = next(iter(keyring.items()))
    assert epoch == "0"
    assert len(base64.b64decode(key_b64)) == 32


@requires_helm
@pytest.mark.fail_slow("30s")
def test_keyring_reuse_guard_present_in_template() -> None:
    # The create-if-absent guarantee relies on a `lookup` guard; assert it exists in source so a
    # refactor cannot silently drop it (upgrade must never regenerate the master key).
    template = (CHART_DIR / "templates" / "secret-pii-keyring.yaml").read_text()
    assert 'lookup "v1" "Secret"' in template
    assert "resource-policy: keep" in template
